INSERT INTO USERS (USERNAME, PASSWORD, AGE, GENDER, ADDRESS)
  VALUES ('Admin', 'Admin@123', 22, 'Male', 'Admin Address');

INSERT INTO MEDICINE (NAME, CATEGORY, QUANTITY)
  VALUES ('Resfenol', 'FEVER', 120);